<?php

namespace Curriculum\CurriculumBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProfilsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfilsRepository extends EntityRepository
{
}
